### ISSUE TITLE
[win32-x86-64] Unable to load library MaaFramework.dll

### ISSUE THREAD

**Issue by Circularorbit** [hanhuoer/maa-framework-java#1]
After deploying the maven project, when I executed the QuickStart class, the result was an exception of java.lang.UnsatisfiedLinkError: Unable to load library MaaFramework.dll.

but the MaaFramework.dll file does exist in project-root/resources/maa/lib inside.

the OS is win64, the cpu is arm64, the jdk is openJDK 17.

at first, I thought the DLL was damaged, but even when I reinstalled the dependencies in the Maven local repository, this error still occurred.

![image](https://github.com/user-attachments/assets/9f17da80-d048-481f-aa3f-bfbd18d4048f)

When I was debugging, I found that he was using maa.win-x86_64

but i don't know how to do debug next, and check it out what problem.

![image](https://github.com/user-attachments/assets/69cb0a82-1f42-4076-bddf-bca5412938e9)

**Comment by Circularorbit** [comment]
I think this may be due to a lack of runtime dependencies with Microsoft, so I used the depands.exe tool to check its DLL and it turned out to be so.

Download link [depends official website](http://www.dependencywalker.com/)
Download link [VC_redist.x64](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version)


OK, the issue was done!!!

**Comment by hanhuoer** [comment]
可以去 `io.github.hanhuoer.maa.Maa`  打个断点看看吗？

看下 osName osArch 这俩变量的值是什么。

因为我这边没有 arm64 的机器，所以之前写的时候可能忽略了这块，导致测试不充分。

讲道理你的环境应该会选择 win-aarch64 呀。

![image](https://github.com/user-attachments/assets/8f90300d-26a3-4389-9ca2-94fee3575f9f)

**Comment by Circularorbit** [comment]
你好，Debug变量如下：

[cid:c5a4bd34-c5cb-4125-aa49-078780547229]

系统信息

[cid:bcba2291-afc0-498b-9de5-78794220af5a]

正常来说，64位ARM架构CPU的osArch才是arch64，

至于为什么英特尔64位x86架构CPU的osArch为什么是amd64，

我在网上查到，它们都是英特尔的别名，即：amd64=x86_64=x64

________________________________
发件人: H ***@***.***>
发送时间: 2024年8月24日 21:11
收件人: hanhuoer/maa-framework-java ***@***.***>
抄送: Ulquiorra ***@***.***>; State change ***@***.***>
主题: Re: [hanhuoer/maa-framework-java] [win32-x86-64] Unable to load library MaaFramework.dll (Issue #1)


可以去 io.github.hanhuoer.maa.Maa 打个断点看看吗？

看下 osName osArch 这俩变量的值是什么。

因为我这边没有 arm64 的机器，所以之前写的时候可能忽略了这块，导致测试不充分。

讲道理你的环境应该会选择 win-aarch64 呀。

image.png (view on web)<https://github.com/user-attachments/assets/8f90300d-26a3-4389-9ca2-94fee3575f9f>

―

**Comment by hanhuoer** [comment]
> I think this may be due to a lack of runtime dependencies with Microsoft, so I used the depands.exe tool to check its DLL and it turned out to be so.
> 
> Download link [depends official website](http://www.dependencywalker.com/) Download link [VC_redist.x64](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version)
> 
> OK, the issue was done!!!

@Circularorbit 你好，请教一下，你这边是安装 [Latest Microsoft Visual C++ Redistributable Version](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version) 之后就可以正常使用了吗？

很奇怪，最近我在 MaaFramework 2.0 版本也遇到同样问题了，在你发之前没见到过，回来看了下才发现是一样的问题。

用 dependencywalker 查了下，确实好多红的 dll，大概几百个吧，但 MaaFramework v1.8.9 也是同样，这就让人想不明白了。

目前我这边测试的都是 win-x86_64，macos 倒是通过的，你最近有使用 v2.0 吗。

- [v2.0.0-beta.4](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-beta.4)
- [v2.0.0-beta.3](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-beta.3)
- [v2.0.0-beta.2](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-beta.2)
- [v2.0.0-beta.1](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-beta.1)
- [v2.0.0-alpha.3](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-alpha.3)
- [v2.0.0-alpha.2](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-alpha.2)
- [v2.0.0-alpha.1](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-alpha.1)

**环境**

Windows 10 
版本	10.0.19045
系统类型	基于 x64 的电脑
处理器	Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz，2601 Mhz，4 个内核，8 个逻辑处理器

Java 11

---

```java
import com.sun.jna.Library;
import com.sun.jna.Native;
import io.github.hanhuoer.maa.util.FileUtils;

public class MaaFrameworkTest {
    public interface MaaController1_8_9 extends Library {
        MaaController1_8_9 INSTANCE = Native.load("C:\\Users\\H\\Downloads\\MaaFW\\1.8.9\\MaaFramework.dll", MaaController1_8_9.class);
    }

    public interface MaaController2_0_0 extends Library {
        MaaController2_0_0 INSTANCE = Native.load("C:\\Users\\H\\Downloads\\MaaFW\\2.0.0-beta.4\\MaaFramework.dll", MaaController2_0_0.class);
    }

    public static void main(String[] args) {
        // System.out.println(MaaController1_8_9.INSTANCE);        
        System.out.println(MaaController2_0_0.INSTANCE);    
		
    }
}

```

<img width="1118" alt="image" src="https://github.com/user-attachments/assets/899536f7-73c1-4857-b677-db9cd067f2d9">

**Comment by moomiji** [comment]
![image](https://github.com/user-attachments/assets/c268ce23-71da-44c2-952e-0f2fa4b1b28e)

https://github.com/lucasg/Dependencies

[MaaFrameworkX64.zip](https://github.com/user-attachments/files/17095047/MaaFrameworkX64.zip)

单独一个 MaaFramework.dll 应该只有 4 个红dll

**Comment by hanhuoer** [comment]
> ![image](https://private-user-images.githubusercontent.com/35213527/369811992-c268ce23-71da-44c2-952e-0f2fa4b1b28e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwODUxMzIsIm5iZiI6MTcyNzA4NDgzMiwicGF0aCI6Ii8zNTIxMzUyNy8zNjk4MTE5OTItYzI2OGNlMjMtNzFkYS00NGMyLTk1MmUtMGYyZmE0YjFiMjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDA5NDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MWJmMThjN2UwZjc0MzhkNDk3MWYyZWM2NWVjM2NlMzE4ODZjZWFkMDNiYjEwMzQyZDc5ZmQ0Yjc4MWU1MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wRZWZ3U_TTmVCdjVd9C79Hf7CbLQKJAbLQFdmOxyg-c)
> 
> https://github.com/lucasg/Dependencies
> 
> [MaaFrameworkX64.zip](https://github.com/user-attachments/files/17095047/MaaFrameworkX64.zip)
> 
> 单独一个 MaaFramework.dll 应该只有 4 个红dll

---

这是我用 `Dependencies` 打开 dll 后的情况，分别是 release 版本的 MaaFramework.dll 和你提供的 MaaFrameworkX64.dll

[MAA-win-x86_64-v2.0.0.zip](https://github.com/MaaXYZ/MaaFramework/releases/download/v2.0.0/MAA-win-x86_64-v2.0.0.zip)

<details>
<summary>展开查看 Release MaaFramework 2.0.0 依赖情况</summary>
<pre>
<img width="1388" alt="image" src="https://github.com/user-attachments/assets/2626133d-3717-41d0-945a-1f1146866bef">
</pre>
</details>

[MaaFrameworkX64.zip](https://github.com/user-attachments/files/17095047/MaaFrameworkX64.zip)

<details>
<summary>展开查看 MaaFrameworkX64.zip 依赖情况</summary>
<pre>
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/838e8f64-abb2-45a0-8e0d-9747c966abed">
</pre>
</details>

**Comment by hanhuoer** [comment]
[[MAA-win-x86_64] 动态链接库(DLL)初始化例程失败](https://github.com/MaaXYZ/MaaFramework/issues/361)

问题找到了，是下面 dll 的版本问题，详情可以参考这个 issue。

- msvcp140.dll
- vcruntime.dll

**Comment by Circularorbit** [comment]
> > I think this may be due to a lack of runtime dependencies with Microsoft, so I used the depands.exe tool to check its DLL and it turned out to be so.
> > Download link [depends official website](http://www.dependencywalker.com/) Download link [VC_redist.x64](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version)
> > OK, the issue was done!!!
> 
> @Circularorbit 你好，请教一下，你这边是安装 [Latest Microsoft Visual C++ Redistributable Version](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version) 之后就可以正常使用了吗？
> 
> 很奇怪，最近我在 MaaFramework 2.0 版本也遇到同样问题了，在你发之前没见到过，回来看了下才发现是一样的问题。
> 
> 用 dependencywalker 查了下，确实好多红的 dll，大概几百个吧，但 MaaFramework v1.8.9 也是同样，这就让人想不明白了。
> 
> 目前我这边测试的都是 win-x86_64，macos 倒是通过的，你最近有使用 v2.0 吗。
> 
> * [v2.0.0-beta.4](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-beta.4)
> * [v2.0.0-beta.3](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-beta.3)
> * [v2.0.0-beta.2](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-beta.2)
> * [v2.0.0-beta.1](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-beta.1)
> * [v2.0.0-alpha.3](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-alpha.3)
> * [v2.0.0-alpha.2](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-alpha.2)
> * [v2.0.0-alpha.1](https://github.com/MaaXYZ/MaaFramework/releases/tag/v2.0.0-alpha.1)
> 
> **环境**
> 
> Windows 10 版本 10.0.19045 系统类型 基于 x64 的电脑 处理器 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz，2601 Mhz，4 个内核，8 个逻辑处理器
> 
> Java 11
> 
> ```java
> import com.sun.jna.Library;
> import com.sun.jna.Native;
> import io.github.hanhuoer.maa.util.FileUtils;
> 
> public class MaaFrameworkTest {
>     public interface MaaController1_8_9 extends Library {
>         MaaController1_8_9 INSTANCE = Native.load("C:\\Users\\H\\Downloads\\MaaFW\\1.8.9\\MaaFramework.dll", MaaController1_8_9.class);
>     }
> 
>     public interface MaaController2_0_0 extends Library {
>         MaaController2_0_0 INSTANCE = Native.load("C:\\Users\\H\\Downloads\\MaaFW\\2.0.0-beta.4\\MaaFramework.dll", MaaController2_0_0.class);
>     }
> 
>     public static void main(String[] args) {
>         // System.out.println(MaaController1_8_9.INSTANCE);        
>         System.out.println(MaaController2_0_0.INSTANCE);    
> 		
>     }
> }
> ```
> 
> <img alt="image" width="1118" src="https://private-user-images.githubusercontent.com/28647233/369620999-899536f7-73c1-4857-b677-db9cd067f2d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0OTkwNjUsIm5iZiI6MTcyNzQ5ODc2NSwicGF0aCI6Ii8yODY0NzIzMy8zNjk2MjA5OTktODk5NTM2ZjctNzNjMS00ODU3LWI2NzctZGI5Y2QwNjdmMmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDA0NDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZjhhYTNlZWY4ZDU3OTczZWVlNzk3NDc4NGFmMjY5YTMwODRlZmZkNjg2YjhiZGRkZTMzMGY3NDhkOGI2ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t8cbtpzmk-DhwxpBjL78K695Q_Q_FLug8rvBb3Ozy7M">

MaaFramework v2.0.0问题找到了就好, 这类问题主要还是版本兼容, 运行环境的问题。
我当时用的是MaaFramework v1.8.9, 主要原因的确是运行环境缺少了vc依赖。

**Comment by sandogeek** [comment]
建议readme加一下解决方案，因为直接按readme流程会报此问题

**Comment by sandogeek** [comment]
另外发现保证system32目录下的msvcp140版本正确的情况下，把java jdk  bin目录下的msvcp140重命名为_msvcp140也可以解决问题

**Comment by hanhuoer** [comment]
> 建议readme加一下解决方案，因为直接按readme流程会报此问题

好主意，晚点我更新一下

**Comment by sandogeek** [comment]
> > 建议readme加一下解决方案，因为直接按readme流程会报此问题
> 
> 好主意，晚点我更新一下

另外可以在加载MaaFramework前检查一下msvcp140.dll的版本，如果不满足要求就抛出一个带解决方案的异常
