### ISSUE TITLE
大佬有更新2.0的计划吗？

### ISSUE THREAD

**Issue by ShutTheFu2kUp** [hanhuoer/maa-framework-java#2]
如题

**Comment by hanhuoer** [comment]
东西写差不多了，目前遇到这个问题，还在解决中。

很奇怪，macos 测试通过，但 windows 就不行，回头我问问那边。

[win10-64 动态链接加载错误](https://github.com/hanhuoer/maa-framework-java/issues/1#issuecomment-2365185993)

**Comment by hanhuoer** [comment]
> 如题

问题找到了，这边测试测试，差不多了再发布。

如果使用过程中也遇到这个问题，可以参考下面这个 issue。

[[MAA-win-x86_64] 动态链接库(DLL)初始化例程失败 #361 - MaaFramework](https://github.com/MaaXYZ/MaaFramework/issues/361#issuecomment-2370262159)

**Comment by leck995** [comment]
期待

**Comment by Circularorbit** [comment]
期待
