### ISSUE TITLE
tasker中resource方法和controller方法为何是每次调用都创建出新的?

### ISSUE THREAD

**Issue by sandogeek** [hanhuoer/maa-framework-java#4]
也就是说这两个方法是用来刷新的？

**Comment by hanhuoer** [comment]
为了保证一致性吧，参考 [tasker.py](https://github.com/MaaXYZ/MaaFramework/blob/b71cc71ed9e9ee0108df82106b208b8874fe686b/source/binding/Python/maa/tasker.py#L58)

我印象中之前有加入 get 方法 `getController` 和 `getResource`，忘记为什么又没了。😂 这就补一下。

**Comment by hanhuoer** [comment]
[Commit fec7930](https://github.com/hanhuoer/maa-framework-java/commit/fec7930c99c6e0afffa3e10fdb3afc8b3f104856)

**Comment by sandogeek** [comment]
看了C# binding,逻辑是获取maa的controller指针与缓存的controller指针比对，不一致就报错，一致就返回缓存的controller，感觉这样更合理点。
```
public required IMaaController<nint> Controller
    {
        get
        {
            MaaTaskerGetController(Handle).ThrowIfNotEquals(_controller.Handle, MaaInteroperationException.ControllerModifiedMessage);
            return _controller;
        }
        set
        {
            ArgumentNullException.ThrowIfNull(value);
            MaaTaskerBindController(Handle, value.Handle).ThrowIfFalse(MaaInteroperationException.ControllerBindingFailedMessage);
            _controller = value;
        }
    }
```

**Comment by hanhuoer** [comment]
我明白你的意思了，建议很好，这样子确实合理一些，晚些我做下调整。👍
